### ISSUE TITLE
Expose full functionality of bsts

### ISSUE THREAD

**Issue by BrianMiner** [klarsen1/MarketMatching#10]
This package is really helpful for convenience of the analysis flow - it would be improved though by exposing all the parameters of bsts. For example, the seasonality component.

**Comment by klarsen1** [comment]
You’re not the first one to ask. Good suggestion. I’ll add that when I find
some time to change this package. If you need it now, it should be easy to
fork and add on your end.

K

**Comment by klarsen1** [comment]
I added this option. you can now pass model arguments.
