### ISSUE TITLE
Error when downloading/installing the repo/library in R.

### ISSUE THREAD

**Issue by nilmolne** [klarsen1/MarketMatching#11]
When running the following line to install the package:
`devtools::install_github("klarsen1/MarketMatching", build_vignettes=TRUE)`

I get the following error:
```
Downloading GitHub repo klarsen1/MarketMatching@master
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >= 
```

I am using **R version 3.4.1** and **devtools_2.0.1**.

Thanks a lot for looking into this issue.

**Comment by rz-hf** [comment]
I am receiving the same error with this package

**Comment by klarsen1** [comment]
Not sure why it’s doing that.

I need to recompile the package. Will try to resolve this over the next
couple of days.

Kim

**Comment by klarsen1** [comment]
seems like this was related to devtools (and some other things). I reverted to devtools 1.11.1. Pls try to install with that version of devtools.

**Comment by rz-hf** [comment]
still have the same issue. I run the following:
`packageurl <- "http://cran.r-project.org/src/contrib/Archive/devtools/devtools_1.11.1.tar.gz"`
`install.packages(packageurl, repos=NULL, type="source")`
`library(devtools)`

I'm using R version 3.5.1.
Thanks in advance for looking into this!

**Comment by klarsen1** [comment]
download from CRAN without redownloading dev tools.
