### ISSUE TITLE
Unexpected error in MarketMatching::inference()

### ISSUE THREAD

**Issue by leungi** [klarsen1/MarketMatching#13]
Thanks first of all for the useful package; I'd used it on several cases and bumped into this recently.

I tried debugging and found my way down to the `CausalImpact()` call; however, I can't find an explanation to the error.

Error: 
```
Error in data.frame(y.model, cum.y.model, point.pred, cum.pred) : 
  arguments imply differing number of rows: 122, 123
```

In `MarketMatching::inference()`, the `ts` variable created, which is passed on to `CausalImpact::CausalImpact(ts, pre.period, post.period, alpha = alpha, model.args = bsts_modelargs)` has `dim()` `122 10`, so not sure where the `123` comes from.

Apologies for not providing a reproducible example as data is confidential; further, toy problems don't have this issue.

Look forward to insights.

**Comment by klarsen1** [comment]
Have you checked for “holes” in your time series input data?

K

**Comment by leungi** [comment]
That was my first suspicion, but there are no NA/NaN/NULL, only zeroes.

The zeroes are not the causes as I realized by adjusting post_end_period to an earlier interval (even with the zeroes in there) avoids the error.

**Comment by klarsen1** [comment]
By holes, I mean that you’re skipping a week or day. No nulls, etc. this
triggers an error.

**Comment by leungi** [comment]
@klarsen1: spot on! 

I did find a hole.

Thanks again for the advise.
