### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by mefergus** [klarsen1/MarketMatching#14]
Lines 374 and 375 of functions.R should be:

#' \item{\code{TestData}}{A \code{vector} with the test market data}
#' \item{\code{ControlData}}{A \code{data.frame} with the data for the control markets}

Currently it is this:
#' \item{\code{TestData}}{A \code{data.frame} with the test market data}
#' \item{\code{TestData}}{A \code{data.frame} with the data for the control markets}

**Comment by klarsen1** [comment]
fixed
