### ISSUE TITLE
v1.1.3 in CRAN

### ISSUE THREAD

**Issue by jmesam** [klarsen1/MarketMatching#20]
Hello,
I'd like to test the prospective_power function but it seems the last version is not available in CRAN yet, and I cannot compile packages from github from my work laptop

Thanks!

**Comment by klarsen1** [comment]
Did you try install_github? Or is it some security thing?

**Comment by jmesam** [comment]
It's a security thing, compile it from Github would require Admin permissions

**Comment by klarsen1** [comment]
I can send you a zipped file with the package. Then you can download and install from there through R Studio.

**Comment by jmesam** [comment]
That'd be awesome :) Thanks

**Comment by klarsen1** [comment]
Which email?

**Comment by jmesam** [comment]
I tried the installation method posted here: https://rdrr.io/github/klarsen1/MarketMatching/

```
install.packages("remotes")
remotes::install_github("klarsen1/MarketMatching")
```
And I could install version 1.1.4  without any permissions issue

Thanks for the support
