### ISSUE TITLE
calculation of MAPE

### ISSUE THREAD

**Issue by sorensje** [klarsen1/MarketMatching#21]
https://github.com/klarsen1/MarketMatching/blob/9174be6bfb3953f85280b70c06fd3caa27824aec/R/functions.R#L149

hey @klarsen1 ,

I love this wrapper you've created - it's very useful! Trying to understand the MAPE calculation. is there a reason you're fitting an lm and taking the residuals of that lm? I tried to reproduce the numbers this helper function reads out, but could not do so.

```{r}
 # make some fake data
v1 <- c(1,3,6)
v2 <- c(2,3,7)


mape_no_zeros <- function(test, ref){
  d <- cbind.data.frame(test, ref)
  d <- subset(d, abs(test)>0)
  return(mean(abs(stats::lm(test ~ ref, data=d)$residuals)/abs(d$test)))
}


mape_hand_calc <- function(test, ref){
  # following https://en.wikipedia.org/wiki/Mean_absolute_percentage_error
  if(length(test) != length(ref)){
    stop("inputs need to be same length")
  }
  
  # setup
  n_points <- length(ref)
  rolling_sum <- 0
  
  # for each time point, get difference between reference and pred value, divide by ref
  # add abs of this to running total
  for(i in 1:n_points){
    rolling_sum <- rolling_sum + abs((ref[i] - test[i]) / ref[i])
  }
  return(rolling_sum / n_points)
}

# show results
mape_hand_calc(v2, v1)
mape_hand_calc(v1, v2)
mape_no_zeros(v1, v2)
mape_no_zeros(v2, v1)

```

also, I don't mean this a contribution, this is just a question

**Comment by klarsen1** [comment]
Hey —

I’m actually going to change this in github over the weekend. Thanks for
catching.

I can’t quite recall — the original version was written some time ago — but
I think my reasoning was to reset the SSE to zero before computing MAPE
after subsetting the data (removing points where the denominator is zero).
So I just used LM for that as a hack.

K

**Comment by klarsen1** [comment]
Fixed

**Comment by sorensje** [comment]
thanks so much for making the update! makes sense now
