### ISSUE TITLE
Weights for data points

### ISSUE THREAD

**Issue by ValdarT** [klarsen1/MarketMatching#23]
Thank you for this library! Is there any way to incorporate weights for data points (e.g., if the daily statistics are based on very different sample sizes, then one might want to weigh these values accordingly in the analysis)?

**Comment by klarsen1** [comment]
Good question. Sorry, this feature does not exist in the package.

K

**Comment by ValdarT** [comment]
Perhaps leave this open as a feature request?

**Comment by klarsen1** [comment]
Makes sense.
