### ISSUE TITLE
Installation failing due to dependency upgrade 

### ISSUE THREAD

**Issue by yuvanpradeep** [klarsen1/MarketMatching#31]
The following dependencies have been updated, causing the MarketMatching package version 1.2.0 to fail.

Boom: 0.9.11 -> 0.9.14
BoomSpikeSlab: 1.2.5 -> 1.2.6

**Comment by SeanRichterWalsh** [comment]
Hi,

I have Boom 0.9.14 and BoomSpikeSlab 1.2.6 installed and MarketMatching 1.2.0 works fine for me.

What error message are you getting when trying to install MarketMatching?

**Comment by klarsen1** [comment]
I'm compiling a new version based on the latest version of R and hope to
publish soon.

**Comment by SeanRichterWalsh** [comment]
Awesome! Thank you.

**Comment by yuvanpradeep** [comment]
> Hi,
> 
> I have Boom 0.9.14 and BoomSpikeSlab 1.2.6 installed and MarketMatching 1.2.0 works fine for me.
> 
> What error message are you getting when trying to install MarketMatching?

bsts is one of the imports of the MarketMatching package and the latest versions of Boom and BoomSpikeSlab are not compatible with bsts I believe.

**Environment:** 
Amazon EMR version: emr-6.11.0
Hadoop 3.3.3, Spark 3.3.2, Hive 3.1.3

**Package Versions:** 
MarketMatching: 1.2.0
bsts: 0.9.9
Boom: 0.9.14
BoomSpikeSlab: 1.2.6

**Error messages:** 
```
create_shared_state_model.cpp:164:64: error: no matching function for call to â€˜BOOM::ConditionallyIndependentSharedLocalLevelPosteriorSampler::ConditionallyIndependentSharedLocalLevelPosteriorSampler(BOOM::ConditionallyIndependentSharedLocalLevelStateModel*, std::vector<BOOM::Ptr<BOOM::MvnBase> >&, std::vector<BOOM::Ptr<BOOM::VariableSelectionPrior> >&)â€™
           state_model_sampler)(state_model.get(), slabs, spikes);
```


```
/home/hadoop/R/x86_64-koji-linux-gnu-library/4.0/Boom/include/Models/StateSpace/Filters/MultivariateKalmanFilterBase.hpp: In instantiation of â€˜void BOOM::MultivariateKalmanFilter<MARGINAL>::ensure_size(int) [with MARGINAL = BOOM::Kalman::ConditionallyIndependentMarginalDistribution]â€™:
create_shared_state_model.cpp:182:1:   required from here
/home/hadoop/R/x86_64-koji-linux-gnu-library/4.0/Boom/include/Models/StateSpace/Filters/MultivariateKalmanFilterBase.hpp:228:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       while(nodes_.size() <=  time) {
make: *** [create_shared_state_model.o] Error 1
ERROR: compilation failed for package â€˜bstsâ€™
* removing â€˜/home/hadoop/R/x86_64-koji-linux-gnu-library/4.0/bstsâ€™
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package â€˜bstsâ€™ had non-zero exit status
Execution halted
```

**Comment by SeanRichterWalsh** [comment]
@yuvanpradeep That is odd. I have bsts 0.9.9 installed also and have no issues using MarketMatching. 

When I load bsts, Boom and BoomSpikeSlab load fine too.

![image](https://github.com/klarsen1/MarketMatching/assets/42702165/a12a3af7-3ae7-4434-8c0e-b4560a4b292b)

**Comment by yuvanpradeep** [comment]
@SeanRichterWalsh

**Failure scenario with the following installation**
Note: This started failing after the upgrade of Boom and BoomSpikeSlab

```
remotes::install_version("MarketMatching", "1.2.0", dependencies = TRUE)
remotes::install_version("tidyverse", "1.3.1", dependencies = TRUE)
remotes::install_version("glue", "1.6.2", dependencies = TRUE)
remotes::install_version("stringr", "1.4.0", dependencies = FALSE)
remotes::install_version("optparse")
```

**Success scenario when I specify the lower versions for Boom and BoomSpikeSlab**
```
remotes::install_version("Boom", version = "0.9.11")
remotes::install_version("BoomSpikeSlab", version = "1.2.5", dependencies = FALSE)
remotes::install_version("zoo", version = "1.8-12")
remotes::install_version("xts", version = "0.13.1")
remotes::install_version("bsts", version = "0.9.9", dependencies = FALSE)
remotes::install_version("assertthat", version = "0.2.1")
remotes::install_version("ggplot2", version = "3.4.4")
remotes::install_version("CausalImpact", version = "1.3.0", dependencies = FALSE)
remotes::install_version("tidyr", version = "1.3.0")
remotes::install_version("dplyr", version = "1.1.4")
remotes::install_version("iterators", version = "1.0.14")
remotes::install_version("doParallel", version = "1.0.17")
remotes::install_version("reshape2", version = "1.4.4")
remotes::install_version("dtw", version = "1.23-1")
remotes::install_version("foreach", version = "1.5.2")
remotes::install_version("MarketMatching", "1.2.0", dependencies = FALSE)
remotes::install_version("tidyverse", "1.3.1", dependencies = TRUE)
remotes::install_version("glue", "1.6.2", dependencies = TRUE)
remotes::install_version("stringr", "1.4.0", dependencies = FALSE)
remotes::install_version("optparse")
```

**Comment by klarsen1** [comment]
Should be fixed when I upload the new package

**Comment by SeanRichterWalsh** [comment]
@yuvanpradeep Oh I see. That is odd. Sorry I can't be of any help to you but as @klarsen1 says, the new version should solve your issue. Have a great day.

**Comment by klarsen1** [comment]
I can't push to CRAN right now since bsts seems to fail CRAN tests on Linux (which means MarketMatching also fails when I try to release). You could download 1.2.1 from GitHub: devtools::install_github("klarsen1/MarketMatching")

**Comment by klarsen1** [comment]
Btw, I'm worried this is a more fundamental issue for people who are not on
Mac or Windows. BSTS won't install when I submit the package for Linux
for example. Maybe try to install from github but not sure it'll work.
