### ISSUE TITLE
Question - Not an Issue!

### ISSUE THREAD

**Issue by BrianMiner** [klarsen1/MarketMatching#5]
Loved the post and this package - thanks for sharing it!

One question I had was the following, to your knowledge is there anything special about structural time series that makes it especially suitable for causal analysis like this, where a model is used to forecast the time series and the differential between forecast and prediction is the estimate of causality? For example, (since I don't really understand structural time series models) could we use a block bootstrap on the same type of data and use say a neural net for the model (the bootstrap providing the prediction intervals t)?

**Comment by klarsen1** [comment]
you probably can. i don't see why not.
