### ISSUE TITLE
no valid data in the post period

### ISSUE THREAD

**Issue by LuciaHrrr** [klarsen1/MarketMatching#7]
I have a dataset with dates spanning from 2018-02-02 to 2018-05-24 and an intervention on 2018-05-04. 

I've set 
start_match_period="2018-02-02"
end_match_period="2018-05-03"
end_post_period = "2018-05-24"
which should be correct but I keep getting this error and have no idea why:

Error in stopif(length(post_period) == 0, TRUE, "ERROR: no valid data in the post period") : 
  ERROR: no valid data in the post period
In addition: Warning message:
In max(date) : no non-missing arguments to max; returning -Inf

@klarsen1 can you please help me out?

**Comment by schoolgurlq-zz** [comment]
Hi - please check the structure of your dataframe to ensure that your data column is a date (and not a factor).

**Comment by klarsen1** [comment]
Might have to do as.Date(<your date variable> , format=“<your format>”)
